<a href="https://colab.research.google.com/github/ucfilho/Metodos_Numericos/blob/master/Distillation_Column_system_01_ago_16_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import numpy.linalg as nl

In [ ]:
'''
Distillation are used to separate a mix of compounds based on different their different boiling temperature. 

The mathematical modeling of such process involve 1000’s of non linear equations. Let us
explore a simplification of this model that is illustrated in figure 3.2. In this example the input mixture
contains three compounds: 30 kg/s of methane (M), 25 kg/s of ethane(E) and 10 kg/s of propane(P).
The input mixture is separated in three out flow streams: the overhead that is rich in methane (90
%), the middle stream rich in ethane (50 %) and the bottom flow rich in propane (70 %). The figure
contains additional information about the mass fraction of each flow, noted xi and the total mass flow
rates of each stream given in kg/s and noted mi
'''

In [2]:
# create the matrix A
A = np. array ([[0.9 ,0.3 ,0.1] ,[0.1 ,0.5 ,0.2] , [0.0 ,0.2 ,0.7]])

# create the right-hand side
feed = np. array ([30.0 ,25.0 ,10.0])

# solve the linear system with np.solve()
x = nl.solve(A,feed)

# print the solution
print(x)

# check the solution
check_sol = np.dot(A,x)
print(check_sol) 
print(feed) 


[17.88461538 45.96153846  1.15384615]
[30. 25. 10.]
[30. 25. 10.]
